spring.application.name=deviceCare

# =========================================================
# BASE DE DATOS
# =========================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/db_device_care
spring.datasource.username=postgre
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================================================
# JPA / HIBERNATE
# =========================================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =========================================================
# JWT
# =========================================================
jwt.secret=cambia_esto_por_una_clave_de_minimo_32_caracteres
jwt.expiration=900000
jwt.refresh-expiration=604800000

# =========================================================
# CLOUDINARY
# =========================================================
cloudinary.cloud-name=tu_cloud_name
cloudinary.api-key=tu_api_key
cloudinary.api-secret=tu_api_secret

# =========================================================
# WEBSOCKET
# =========================================================
spring.websocket.enabled=true